# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Direct integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Direct Integration

  pod 'OguryAds'
  pod 'OguryChoiceManager'

end
