# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'Objective C sample.xcworkspace'

project 'Direct integration/Direct integration'
project 'Admob integration/Admob integration'

target 'Direct integration' do
  project 'Direct integration/Direct integration'
  use_frameworks!

  # Pods for Direct Integration
  pod 'OgurySdk', '~> 2.0.0'
end


target 'Admob integration' do
  project 'Admob integration/Admob integration'
    use_frameworks!

    # Pods for Admob Integration
    pod 'OguryMediationGoogleMobileAds', '~> 2.1.0.0'
    pod 'Google-Mobile-Ads-SDK', '~> 9'
end

